// <auto-generated />
namespace Galeno.Infraestructura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migracion2907 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracion2907));
        
        string IMigrationMetadata.Id
        {
            get { return "202007290431060_migracion2907"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
